#!/usr/bin/env python3
"""PreToolUse gate: name the skills and rules that own a path, at the moment it is edited."""

import hashlib
import json
import os
import sys
import tempfile

# (path prefix or exact path, skills, rule files)
MAP = [
    ("backend/tests/", ["pest-testing", "testing-best-practices"], ["testing.md"]),
    ("backend/app/Data/", ["laravel-data"], ["api-and-data.md"]),
    ("backend/app/Http/", ["laravel-attributes"], ["api-and-data.md"]),
    ("backend/routes/api.php", [], ["api-and-data.md"]),
    ("backend/app/Actions/Calendar/", ["calendar-sync", "laravel-actions"], ["domain-model.md"]),
    ("backend/app/Actions/", ["laravel-actions"], ["domain-model.md"]),
    ("backend/app/Models/", ["laravel-attributes"], ["domain-model.md"]),
    ("backend/database/migrations/", [], ["domain-model.md"]),
    ("backend/app/Support/Ai/", ["ai-layer-changes"], ["ai-layer.md"]),
    ("backend/app/Contracts/AiProvider.php", ["ai-layer-changes"], ["ai-layer.md"]),
    ("backend/config/ai.php", ["ai-layer-changes"], ["ai-layer.md"]),
    ("backend/app/Enums/Ai/", ["ai-layer-changes"], ["ai-layer.md"]),
    ("backend/app/Support/NextAction/", ["next-action-resolver"], []),
    ("backend/app/Support/Calendar/", ["calendar-sync"], []),
    ("backend/config/calendar.php", ["calendar-sync"], []),
    ("backend/resources/js/", ["inertia-react-development", "wayfinder-development", "tailwindcss-development"], ["product-invariants.md"]),
    ("backend/app/Enums/", [], ["product-invariants.md"]),
    ("mobile/", ["expo-react-native"], ["product-invariants.md", "toolchain.md"]),
    ("mobile/app/", ["expo-router"], []),
    ("mobile/src/api/", ["expo-data-fetching"], []),
    ("mobile/package.json", ["expo-upgrade"], []),
    (".eas/", ["eas-workflows"], []),
    ("packages/shared/", ["generated-artifacts"], ["product-invariants.md", "toolchain.md"]),
    ("backend/compose.yaml", ["generated-artifacts"], ["toolchain.md"]),
    ("backend/vite.config.ts", ["vite"], ["toolchain.md"]),
    ("backend/phpstan.neon", ["phpstan-larastan"], []),
    (".ai/plans/", ["slice-workflow"], ["general.md"]),
    (".ai/skills/", ["writing-for-agents"], []),
    (".ai/rules/", ["writing-for-agents"], ["general.md"]),
]

# Owned by a command. Editing one is reverted by the next run of its generator.
GENERATED = {
    "packages/shared/src/generated.ts": "npm run types:generate, from the PHP Data classes",
    "packages/shared/src/typescript-transformer-manifest.json": "npm run types:generate",
    "backend/resources/js/actions/": "Wayfinder, from the controllers",
    "backend/resources/js/routes/": "Wayfinder, from routes/*.php",
    "backend/resources/js/wayfinder/": "Wayfinder",
    ".ai/guidelines.md": "npm run boost:update",
    ".claude/skills/": "npm run boost:update, from .ai/skills",
}

PHP_ALWAYS = (["laravel-attributes", "laravel-best-practices"], ["general.md"])


def emit(payload):
    print(json.dumps(payload))
    sys.exit(0)


def seen(session, key):
    path = os.path.join(tempfile.gettempdir(), "claude-skill-gate-" + hashlib.sha256(session.encode()).hexdigest()[:16])
    fired = set()
    if os.path.exists(path):
        with open(path) as handle:
            fired = set(handle.read().split("\n"))
    if key in fired:
        return True
    fired.add(key)
    with open(path, "w") as handle:
        handle.write("\n".join(sorted(fired)))
    return False


def main():
    try:
        event = json.load(sys.stdin)
    except (ValueError, OSError):
        emit({})

    root = os.environ.get("CLAUDE_PROJECT_DIR", "")
    target = event.get("tool_input", {}).get("file_path") or ""
    if not target or not root:
        emit({})

    try:
        rel = os.path.relpath(os.path.realpath(target), os.path.realpath(root))
    except ValueError:
        emit({})
    if rel.startswith(".."):
        emit({})

    for path, generator in GENERATED.items():
        if rel == path or rel.startswith(path):
            emit({"hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "ask",
                "permissionDecisionReason": (
                    f"{rel} is generated by {generator}. Hand edits are reverted by the next run. "
                    "Change the source and regenerate — see the generated-artifacts skill."
                ),
            }})

    skills, rules = [], []
    for path, matched_skills, matched_rules in MAP:
        if rel == path or rel.startswith(path):
            skills += matched_skills
            rules += matched_rules

    if rel.endswith(".php") and rel.startswith("backend/app/"):
        skills += PHP_ALWAYS[0]
        rules += PHP_ALWAYS[1]

    skills = list(dict.fromkeys(skills))
    rules = list(dict.fromkeys(rules))
    if not skills and not rules:
        emit({})

    key = rel.split("/")[0] + "|" + ",".join(skills + rules)
    if seen(str(event.get("session_id", "none")), key):
        emit({})

    lines = [f"About to edit {rel}."]
    if skills:
        lines.append("Skills that own this path: " + ", ".join(skills) + ". Invoke any you have not read this session.")
    if rules:
        lines.append("Rules that bind it: " + ", ".join(".ai/rules/" + name for name in rules) + ".")

    emit({"hookSpecificOutput": {"hookEventName": "PreToolUse", "additionalContext": " ".join(lines)}})


main()
